labels:
    app: piyapan
spec:
  replicas: 1

containers:
    image: piyapanker/nodeweb:2.0

limits:
  memory: "512Mi"
  cpu: "210m"
requests:
  memory: "256Mi"
  cpu: "200m"

ingressClassName: nginx

service:
  name: svc-custerip

path: /index

selector:
  app: piyapan

minReplicas: 1
maxReplicas: 2
targetCPUUtilizationPercentage: 75

