name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        required: true
        default: "dev"
        options:
          - dev
          - sit
          - sit2
          - uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Running the workflow with parameter: ${{ github.event.inputs.env }}"
