name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Description of the parameter'
        required: true
        default: 'Default value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Running the workflow with parameter: ${{ github.event.inputs.parameter_name }}"
