name: Lab-piyapan
on:
  push:
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: check github environment
        run: hostname
  deploy: 
    runs-on: piyapan
    steps:
      - name: check github environment
        run: hostname