name: Lab-Piyapan
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input your software version'
        required: true
        default: '1.0.0'
        type: string
  # push:
  #   branches:
  #     - main
env:
  WORDING: "Piyapan"

jobs:
  build: 
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    outputs:
      image-version: ${{ steps.create-variable.outputs.image-version }}
      developer: ${{ github.actor }}
    steps:
    
      - name: check github environment
        run: hostname
      
      - name: create-variable
        id: create-variable
        run: |
          echo "BUILD_ARGS=prod-1.0.0" >> $GITHUB_ENV
          echo "::set-output name=image-version::prod-1.0.0"
      - name: build application
        run: echo "build for ${{ env.WORDING }} by $BUILD_ARGS "

  deploy: 
    runs-on: self-hosted
    needs: build
    if: ${{ always() }}
    steps:
      - name: wait for Approve    
        uses: trstringer/manual-approval@v1
        id: check-approval
        with:
          # secret: ${{ github.TOKEN }}
          approvers: "piyapm49, manowpsr"
          minimum-approvals: 1

      - name: check github environment
        run: hostname
        
      - name: deploy app
        run: echo "deploying app version ${{ needs.build.outputs.image-version}} Developer by ${{ needs.build.outputs.developer }}" 