name: piyapan-lab
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input your software version'
        required: true
        default: '2.0'
        type: string

jobs:
  prepare:
   runs-on: self-hosted
   steps:
     - name: Set Tag on Workflow Dispatch
       if: github.event_name == 'workflow_dispatch'
       run: echo "${{ github.event.inputs.version }}"

  build:
    needs: prepare
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: piyapanker
          password: ${{ secrets.DOCKER_PIYAPAN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: images/Dockerfile
          push: true
          tags: piyapanker/nodeweb:${{ github.event.inputs.version }} 

          #  tags: piyapanker/nodeweb:${{ github.run_number }} 


  
  # deploy:
  #   needs: prepare
  #   runs-on: self-hosted
  #   steps:
  #     - name: minikubestart
  #       run: |
  #        minikube start
  #        kubectl get node
  #     - name: showlist
  #       run: |
  #         ls -la
  #     - name : deploytest
  #       run: kubectl apply -f test/deployment.yaml