name: piyapan-lab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: piyapanker
          password: ${{ secrets.DOCKER_PIYAPAN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: images/Dockerfile
          push: true
          tags: piyapanker/nodeweb:${{ github.run_number }} 
  
  deploy:
    runs-on: self-hosted
    steps:
      - name: showlist
        run: |
         pwd
         ls
         cd test
         ls

      # - name: deploy
      #   run: kubectl apply -f deployment.yaml